## Nomor 1

In [15]:
import numpy as np
import pandas as pd

In [233]:
mulai=int(input("Mulai:"))
selesai=int(input("Selesai:"))

Mulai:1
Selesai:28


In [234]:
np.arange(mulai,selesai)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [235]:
np.arange(mulai,selesai).reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [236]:
np.arange(mulai,selesai).reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

## Nomor 2

In [241]:
banyak_data=int(input("Banyak Data:"))
mulai=int(input("Mulai:"))
selesai=int(input("Selesai:"))

Banyak Data:16
Mulai:1
Selesai:50


In [242]:
arr_1d=np.random.randint(mulai, selesai, banyak_data)
arr_1d

array([18, 38,  6,  4, 42, 10, 45, 28, 19, 29,  8, 47,  5, 26, 37, 39])

In [251]:
arr_2d=arr_1d.reshape(4,-1) ### bingung disininya yg bagian 4 itu harusnya ngga statis kan, kebetulan aja contoh jumlah data 16 
arr_2d

array([[18, 38,  6,  4],
       [42, 10, 45, 28],
       [19, 29,  8, 47],
       [ 5, 26, 37, 39]])

In [283]:
### ini cara desperate kak, ga nemu belom nangkep logic untuk cara simpelnya. maafkan

a=arr_2d[0][::-1]
b=arr_2d[1][::-1]
c=arr_2d[2][::-1]
d=arr_2d[3][::-1]

In [292]:
e=np.append(a,b)
f=np.append(c,d)

g=np.append(e,f)
g=g.reshape(4,-1) ### ini sama bingungnya dgn yg di atas itu
g

array([[ 4,  6, 38, 18],
       [28, 45, 10, 42],
       [47,  8, 29, 19],
       [39, 37, 26,  5]])

## Nomor 3

In [44]:
arr=np.ones((10,10))*4
arr

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [45]:
arr[1:-1,1:-1] = 0
arr

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

## Nomor 4

In [224]:
nilai_index=['a b c d e f g h i j k l m n o p q r s t u v w x y z'.split()]
nilai_data=np.arange(1,27)
pd.Series(index=nilai_index, data=nilai_data)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

## Nomor 5

In [75]:
value=np.random.randint(1,5,100)
pd.Series(data=value)

0     4
1     1
2     2
3     2
4     3
     ..
95    3
96    1
97    3
98    2
99    1
Length: 100, dtype: int32

In [76]:
s1=pd.Series(data=value)
s1.value_counts()

4    29
1    27
3    25
2    19
dtype: int64

In [77]:
s1.value_counts().head(2)

4    29
1    27
dtype: int64

In [223]:
pd.DataFrame(value).value_counts().reset_index(name=('Frequency')).head(2)

0  Frequency
0  4         29
1  1         27

## Nomor 6

In [101]:
import seaborn as sns

In [106]:
mpg=sns.load_dataset('mpg')

In [107]:
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [109]:
mpg.describe(include=object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [123]:
print(mpg.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')


In [127]:
mpg.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

## Nomor 7

In [128]:
import seaborn as sns

In [129]:
mpg=sns.load_dataset('mpg')

In [133]:
mpg[mpg['horsepower'].isnull()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [136]:
index_num=mpg[mpg['horsepower'].isnull()].index
index_num

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

## Nomor 8

In [137]:
import seaborn as sns

In [138]:
mpg=sns.load_dataset('mpg')

In [140]:
mpg.groupby('model_year')['horsepower'].mean()

model_year
70    147.827586
71    107.037037
72    120.178571
73    130.475000
74     94.230769
75    101.066667
76    101.117647
77    105.071429
78     99.694444
79    101.206897
80     77.481481
81     81.035714
82     81.466667
Name: horsepower, dtype: float64

## Nomor 9

In [141]:
import seaborn as sns

In [142]:
mpg=sns.load_dataset('mpg')

In [151]:
mpg['horse_origin']=['lower ' if i<=105 else 'upper ' for i in mpg['horsepower']]+(mpg['origin'])
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  horse_origin  
0            70     usa  chevrolet chevelle malibu     upper usa  
1            70     usa          buick skylark 320     upper usa  
2            70     usa         plymouth satellite     upper usa  
3            70     usa              amc rebel sst     upper usa  
4            70     usa                ford torino     upper usa  
..          ...     ...                        ...           ...  
393          82     usa            ford mustang gl     lower usa  
394          82  europe                  vw pickup  lower europe  
395          82     usa              dodge rampage     lower usa  
396          82     usa                ford ranger     lower usa  
397          82     usa                 chevy s-10     lower usa  

[398 rows x 10 columns]

## Nomor 10

In [152]:
import seaborn as sns

In [156]:
mpg=sns.load_dataset('mpg')

In [207]:
mpg.groupby('origin')['weight'].agg(['mean', 'std', 'sum','count', 'min', 'max']).reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140